import hashlib, json, platform, subprocess, tarfile
from pathlib import Path
root=Path(__file__).resolve().parent
meta=json.loads((root/'metadata.json').read_text())
summary=json.loads((root/'summary.json').read_text())
meta['machine']=subprocess.check_output(['sysctl','-n','machdep.cpu.brand_string'],text=True).strip()
meta['platform']=platform.platform()
meta['rust']=subprocess.check_output(['rustc','--version'],text=True).strip()
meta['build']='Cargo default release profile, --locked, no RUSTFLAGS override. Identical Cargo locks. Each source copy forced to rebuild and its Compiling roc log checked before binary capture.'
meta['source_copy_changes']='Append an empty [workspace] table to each root manifest to isolate it from the enclosing workspace; add the identical examples/ready_poll_probe.rs. Production source is unmodified at each recorded commit.'
meta['statistics']='Geometric mean of five process medians, each from nine samples. Paired process log ratios; 95% paired cluster bootstrap, 10000 resamples of five process pairs. Variant order randomized within each pair; case order reversed in odd-numbered pairs. This is not an end-to-end or multiworker benchmark.'
for label in ['main','pr11']:
    p=root/label/'source.tar.gz'
    with tarfile.open(p,'w:gz')as tar:
        for name in ['src','Cargo.toml','Cargo.lock','examples/ready_poll_probe.rs']:
            tar.add(root/label/name,arcname=name)
    meta.setdefault('source_archive_sha256',{})[label]=hashlib.sha256(p.read_bytes()).hexdigest()
(root/'metadata.json').write_text(json.dumps(meta,indent=2)+'\n')
lines=['# PR #11 current scan-path ablation','',f"Compare main `{meta['source_commits']['main']}` with exact PR #11 `{meta['source_commits']['pr11']}`. Only the PR #11 scan polling change and its tests differ. Both use Arrow 59.3.0 and asyncband 0.7.3.",'',f"Measured on {meta['machine']}, {meta['rust']}. Production source snapshots, identical probe source, locks, logs, binary/source hashes and all 360 timing samples are included. Binaries stay local.",'','## Results','','Time is nanoseconds per batch; lower is better. Five independent process medians are aggregated geometrically. Reduction intervals use paired process bootstrap.','','| Case | main ns/batch | PR #11 ns/batch | Saved ns/batch | Reduction | 95% interval |','|---|---:|---:|---:|---:|---:|']
for mode,r in summary.items():
    lo,hi=r['paired_bootstrap_95_percent']
    lines.append(f"| {mode} | {r['main_ns']:.1f} | {r['pr11_ns']:.1f} | {r['saved_ns']:.1f} | {r['reduction_percent']:.1f}% | {lo:.1f}% to {hi:.1f}% |")
lines += ['', '## Scope and interpretation','', '- `ready`: a consumer immediately returns a shared 2048-row Int64 batch. Measures the actual public ScanExec next_batch path, including its boxed futures, consumer call, batch clone/drop and identical correctness checks.', '- `ready_channel`: 100000 batches are queued in the actual scan_channel before timing; receiver drains already-ready items. Queue creation, producers and prefill are excluded.', '- `ready_sum`: the ready path followed by Arrow SUM over 2048 Int64 values. This is a synthetic scan-plus-kernel loop, not Roc aggregation or a SQL query.', '- `pending_once`: a synthetic consumer returns Pending once and calls wake_by_ref, then returns Ready. This checks wake/re-poll overhead, with no disk, network or producer latency. Its percentage must not be interpreted as a real I/O speedup.', '', 'Every timed batch is checked for 2048 rows and original column ArrayRef identity. ready_sum also verifies the exact total 2096128. Setup and finalization are outside timing. Each of five process pairs uses a randomized variant order, with reversed case order in alternating pairs; each case has 3000 warm-up reads and nine samples of 100000 reads. The two binaries run sequentially. Source rebuilds and binary hashes are recorded.', '', 'The already-ready channel case saves about 23 ns per batch. At 2048 rows per batch, one million rows requires about 489 reads, implying roughly 0.011 ms of saved scan-entry overhead under this synthetic setup. This is an illustration, not a measured SQL-query result. Storage, decode, filtering, grouping, pipeline scheduling, contention and real asynchronous waits are excluded. A 21% decrease in this small scan-entry component does not imply a 21% query improvement. The cancellation regression tests remain in the measured PR source; this timing probe does not replace them.', '', 'The whole patch also removes fuse/select_biased machinery; these measurements compare complete revisions and do not isolate how much comes specifically from avoiding cancellation waiter registration versus other code generation changes.', '', '## Reproduction','', 'The source archives are standalone copies with an empty workspace table added identically for isolation. Extract either archive and run:', '', '```sh', 'cargo build --locked --release --example ready_poll_probe', 'target/release/examples/ready_poll_probe', 'target/release/examples/ready_poll_probe reverse', '```', '', 'build.py and run.py record the original local paths and paired run procedure; metadata.json records exact identities. Raw CSVs contain all nine samples for each case in each process. summary.json retains each process median and bootstrap intervals.', '']
(root/'README.md').write_text('\n'.join(lines))
print((root/'README.md').read_text()[:1700])
