import hashlib, io, json, math, platform, statistics, subprocess, tarfile
from pathlib import Path
root=Path(__file__).resolve().parent;repo=Path('/Users/zenotme/.codex/worktrees/datafusion-optimization-prs/Roc')
a=json.loads((root/'summary.json').read_text());b=json.loads((root/'paired/summary.json').read_text())
meta=json.loads((root/'metadata.json').read_text());pair=json.loads((root/'paired/metadata.json').read_text())
core={'main':'291317e1c4ee43ca7a613f0a532b1f35fae5aab4','count':'0ddd08565871b7e53faa09f738d0cfa25579635c','sum':'c0fce16','reuse':'b3cdd89314ec5808a6525bd03b16c460133bb2f4','fused':'37708712d41b2a51ab30ca951ca98c1e144b3274'}
identities={}
for label,short in core.items():
 sha=subprocess.check_output(['git','rev-parse',short],cwd=repo,text=True).strip();local=(meta['variants'].get(label) or pair['variants'][label])['local_source_commit']
 assert subprocess.check_output(['git','diff',sha,local,'--','src','tests'],cwd=repo)==b''
 raw=subprocess.check_output(['git','archive',sha,'src','tests','Cargo.toml','Cargo.lock'],cwd=repo);p=root/(label+'-core-source.tar.gz')
 with tarfile.open(fileobj=io.BytesIO(raw)) as src:
  with tarfile.open(p,'w:gz') as dst:
   for member in src.getmembers():dst.addfile(member,src.extractfile(member) if member.isfile() else None)
 identities[label]={'core_commit':sha,'local_commit':local,'src_tests_match_exactly':True,'core_archive_sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for phase in [root,root/'paired']:
 m=json.loads((phase/'metadata.json').read_text())
 for label in m['variants']:
  source=phase/label/'source';p=phase/label/'local-source.tar.gz'
  with tarfile.open(p,'w:gz') as archive:
   for name in ['src','tests','integrations','Cargo.toml','Cargo.lock']:archive.add(source/name,arcname=name)
  m['variants'][label]['local_archive_sha256']=hashlib.sha256(p.read_bytes()).hexdigest()
 m['environment']={'date':'2026-10-07','machine':subprocess.check_output(['sysctl','-n','machdep.cpu.brand_string'],text=True).strip(),'memory_bytes':int(subprocess.check_output(['sysctl','-n','hw.memsize'],text=True)),'platform':platform.platform(),'rust':subprocess.check_output(['rustc','--version'],text=True).strip(),'arrow':'59.3.0','datafusion':'55.1.0','core_identities':identities}
 m['validation']={'native_core_release_tests':130,'fused_core_release_tests':132,'native_and_fused_all_targets_pass':True,'datafusion_integration_local_only':True,'all_timed_schema_and_value_checks_passed':True,'fresh_workspace_wide_tests':False}
 (phase/'metadata.json').write_text(json.dumps(m,indent=2)+'\n')
lines=['# Global SUM execution-path diagnosis and ablation','','October 7, 2026. Core changes follow pending [#18](https://github.com/ZENOTME/Roc/pull/18): [#34](https://github.com/ZENOTME/Roc/pull/34) binds global SUM to native checked loops and retains zero group IDs; [#35](https://github.com/ZENOTME/Roc/pull/35) adds a fused prefix-safety bound for integer SUM. Main is unchanged. The DataFusion integration, complete local source archives and executables remain local.','','## Question and storage controls','','Why does the ungrouped SUM/COUNT query remain slower after batch COUNT? Run the unchanged SQL with the same optimized DataFusion logical plan, then execute it through native DataFusion or the Roc converter. Parquet plans scan only `value`; neither plan has a filter or an opportunity for predicate/row-group skipping. Both use DataFusion table-provider scans with the same projection. Native aggregate modes are Single at one thread and Partial/Final at four threads. Roc uses worker-local accumulation and the existing merge path.','','```sql','SELECT SUM(value) AS total, COUNT(value) AS count FROM p','```','','Decode the same single column once, outside timers, and register those exact batches as a resident MemTable `m`, distributed round-robin over the same number of partitions. Repeat the query against `m` to remove Parquet/decompression costs. This is an isolation experiment, not an additive exact accounting of I/O and CPU time. The gap remains almost unchanged at one thread: main is about 14.85 ms behind on Parquet and 14.95 ms behind on resident batches. After batch COUNT, those gaps are about 7.04 and 7.21 ms. Aggregation, rather than a missing storage pushdown, explains the large gap in this query.','','## First experiment: isolate COUNT, SUM and zero IDs','','Four stages, eight process replicas per stage, ten samples per case/engine. Two randomized cyclic Latin squares balance every stage twice at every position. The three engines (native DF, default Roc, Roc with voluntary yield disabled) rotate within each sample. Values are geometric means of per-process medians. Positive reduction means less Roc elapsed time. All observations are retained.','','| Threads | Main Roc ms | Batch COUNT ms | Native global SUM ms | Retained zero IDs ms | DF control at last stage ms | Last stage vs DF |','|---:|---:|---:|---:|---:|---:|---:|']
for t in [1,4]:
 x=a[f'p/{t}t']['stages'];lines.append(f"| {t} | {x['main']['roc_ms']:.2f} | {x['count']['roc_ms']:.2f} | {x['sum']['roc_ms']:.2f} | {x['reuse']['roc_ms']:.2f} | {x['reuse']['datafusion_ms']:.2f} | {x['reuse']['roc_gap_percent']:+.2f}% |")
lines += ['','| Isolated step | 1t elapsed reduction | 1t paired 95% interval | 4t elapsed reduction | 4t paired 95% interval |','|---|---:|---:|---:|---:|']
for label,title in [('count','Batch COUNT (#18)'),('sum','Bound native checked SUM (#34)'),('reuse','Retain zero IDs (#34)')]:
 x=a['p/1t']['stages'][label];y=a['p/4t']['stages'][label];lo,hi=x['stage_reduction_95_percent'];l2,h2=y['stage_reduction_95_percent'];lines.append(f"| {title} | {x['stage_elapsed_reduction_percent']:.2f}% | {lo:.2f}–{hi:.2f}% | {y['stage_elapsed_reduction_percent']:.2f}% | {l2:.2f}–{h2:.2f}% |")
lines += ['','The old SUM loop reads group IDs, tests per-group validity and writes group state for each valid value. The new global kernel is selected once at construction, keeps a native running value local, and uses Arrow validity slices to visit contiguous valid values. Integer addition stays checked. Float64 preserves the first value (including signed zero) and the original addition order. Shared FILTER-before-argument preparation, casts, grouped updates and merges are retained. Unlike closed #15, this introduces no separate expression-execution route or duplicated FILTER preparation.','','The global ID vector remains part of the existing update interface. Its owner has a fixed Global index and only this index writes that vector, so existing entries are already zero. Retain them and initialize only growth; batch shrink/grow and merge sizes are tested. The query gain is small (about 0.8%), but this removes repeated writes with a small change and no new state representation.','','## Second experiment: fuse the safety proof and reduction','','Ten balanced paired processes per variant, five baseline-first/five candidate-first in randomized order. Identical captured probe source for both builds. Ten timed samples per case/engine after two warmups. This experiment remeasures #34 rather than comparing timestamps across experiments.','','| Threads | #34 Roc ms | Fused Roc ms | DF control ms | Fused Roc vs DF | Roc reduction vs #34 | Paired reduction 95% interval |','|---:|---:|---:|---:|---:|---:|---:|']
for t in [1,4]:
 x=b[f'p/{t}t']['stages'];y=x['fused'];lo,hi=y['stage_reduction_95_percent'];lines.append(f"| {t} | {x['reuse']['roc_ms']:.2f} | {y['roc_ms']:.2f} | {y['datafusion_ms']:.2f} | {y['roc_gap_percent']:+.2f}% | {y['stage_elapsed_reduction_percent']:.2f}% | {lo:.2f}–{hi:.2f}% |")
lines += ['','Negative gap means Roc is faster. Within candidate processes, the 95% interval for Roc vs DF is −1.35% to −0.62% at one thread and −5.83% to −5.10% at four threads. The one-thread DF control changes −0.70% between builds, so the raw 3.40% Roc reduction is not all attributed to the kernel: normalizing to the paired DF control gives a 2.72% improvement (2.26–3.32%). Four-thread normalized improvement is 2.73% (2.35–3.09%). These intervals resample process-level paired log ratios, not individual timings as independent observations.','','For Int64, the fused scan computes a conservative magnitude bound and wrapping subtotal together. Let `n` be the valid count, `s` the existing sum, and `B = OR(v XOR (v >> 63)) + 1`. Then `B >= abs(v)` for every valid value. Compute `room = min(MAX - s, s - MIN)` in i128/u128. If `n * B <= room`, every valid prefix fits: its absolute change is at most `n * B`. UInt64 uses `B = OR(v)` and `room = MAX - s`. Bound multiplication fits u128 for the supported native/usize widths.','','The scan may include arbitrary NULL payloads. Subtract their wrapping subtotal using Arrow BooleanBuffer inversion and set-index iteration. Modulo-2^64 subtraction cancels ignored payloads even if raw subtotals wrapped; the bound proves the final logical sum and every logical prefix fit. NULL payloads can conservatively reject the fast path, but cannot cause an execution error. If the proof fails, run the native sequential checked loop and retain its successful prefix on overflow. Empty/all-NULL batches preserve state. Float64 and grouped kernels do not use the bound.','','The captured **actual core-library** disassembly shows vector `add.2d` and `eor/orr.16b` reductions in the fused Int64 scan. The fallback retains `adds` / `b.vs` checks. No explicit SIMD or unsafe code is added. This is a Roc optimization; native DF currently calls Arrow wrapping SUM. Sources: [DataFusion 55.1.0 SUM](https://github.com/apache/datafusion/blob/55.1.0/datafusion/functions-aggregate/src/sum.rs), [Arrow 59.3.0 aggregate kernels](https://github.com/apache/arrow-rs/blob/59.3.0/arrow-arith/src/aggregate.rs).','','## Resident query and remaining limits','','| Threads | #34 Roc ms | Fused Roc ms | DF ms | Fused Roc vs DF |','|---:|---:|---:|---:|---:|']
for t in [1,4]:
 x=b[f'm/{t}t']['stages'];y=x['fused'];lines.append(f"| {t} | {x['reuse']['roc_ms']:.3f} | {y['roc_ms']:.3f} | {y['datafusion_ms']:.3f} | {y['roc_gap_percent']:+.2f}% |")
lines += ['','The one-thread resident improvement is 40.14%, showing the kernel gain directly. The four-thread resident query remains about 0.118 ms / 15.83% slower. This residual is not localized to a specific scheduling/merge operation; do not label it proven scheduler overhead. Disabling voluntary yields provides no stable improvement in the full-path controls (candidate resident 4t medians: default 0.865 ms, disabled 0.869 ms). There is no justified yield change in these PRs.','','These results establish a modest win for the measured warm-cache Parquet SUM/COUNT query, not a universal engine ranking. Int64 input is bounded to ±100000 with NULL every 17th row. Near-limit data may fail the conservative proof and pay the preflight scan before the checked fallback. Float64, UInt64 throughput, different NULL distributions, high-cardinality grouping, joins and spilling are not benchmarked here. A single-thread narrow/non-null workload can have a different relative result. Integer overflow behavior remains intentionally stricter than native DF.','','## Kernel controls and rejected implementations','','The kernel probe includes the exact accumulator source in its own compilation module. It excludes expression, storage and pipeline costs, and its inlining context differs from the library. Full-path timings execute the actual core library; only the latter establish query-level gains. Arrow wrapping controls are not proposed semantic changes. All inputs in the timing suite are overflow-free.','','Candidate-phase one-thread microprobe geometric means of ten process medians:','','| Kernel control | ms over 4M decoded values |','|---|---:|']
kernels={}
for i in range(10):
 r=json.loads((root/'paired/fused'/f'process-{i}.json').read_text());c=next(x for x in r['results'] if x['threads']==1)
 for k,v in c['kernels'].items():kernels.setdefault(k,[]).append(statistics.median(v))
for k,vals in kernels.items():lines.append(f"| {k} | {math.exp(statistics.mean(math.log(v) for v in vals)):.3f} |")
lines += ['','The two-pass range-check + Arrow SUM, dense correction + Arrow SUM, guarded wrapping slices, and deferred overflow-flag prototypes do not beat the native checked slice loop; they are not shipped. The useful version fuses bound + subtotal and corrects only ignored payloads. Preliminary JSON results are retained separately; their binaries were not captured and their compile-time source hash was unset, so they are exploratory rather than primary evidence. The final paired binaries capture all controls with source and executable hashes.','','## Validation and artifacts','','- Core-only #34 head: 130 release tests; #35 head: 132 release tests. All-target compilation passes for both. Source/tests match their local compiled snapshots exactly. Fresh full-workspace tests were not rerun; schema/value checks pass after every timed local integration query.','- New regressions cover sliced validity/all-NULL/empty batches, varying global ID lengths, casts/partial merges, Float64 first signed zero/order/NULL payloads, signed and unsigned cross-batch overflow/successful prefixes, and arbitrary NULL payloads whose raw subtotal wraps. A deterministic test exercises 128 small/extreme cases per integer type with sliced bitmaps and repeated updates.','- [metadata.json](metadata.json) and [paired/metadata.json](paired/metadata.json) record source identities, lockfile/build hashes, hardware, compiler, input-file checksums and process orders. [summary.json](summary.json) records four-stage medians/intervals; [paired/summary.json](paired/summary.json) records final paired medians, intervals and control-normalized effects.','- All process JSONs, build logs, core test/check logs and the two actual core Int64 disassemblies are retained. The first experiment has 3840 full-path timings + 6400 kernel timings; the second has 2400 + 4400. No samples were trimmed.','- Core source archives contain src/tests and production manifests, without the integration. Full local-source archives and binaries stay local. Compiled lockfiles include the private DataFusion harness; their exact digest is recorded separately. Public artifacts are evidence, not a standalone benchmark package; reproduction requires the preserved local harness/archive and original input files.','- build.py / run.py reproduce the first experiment; paired_build.py / paired_run.py reproduce the final paired experiment; normalize.py adds control-normalized statistics; document.py assembles this evidence. They refer to the captured local probe. The main experiment uses batch size 8192, 4M rows in eight Snappy/plain/non-dictionary files, row groups 65536, two warmups and 1/4 Tokio threads. SQL/planning/conversion/Roc graph construction are excluded, full execution and output extraction included. Correctness checks are outside timers.','','Core snapshots:','']
for label,v in identities.items():lines.append(f"- {label}: `{v['core_commit']}`; local snapshot `{v['local_commit']}`; [{label}-core-source.tar.gz]({label}-core-source.tar.gz).")
(root/'README.md').write_text('\n'.join(lines)+'\n')
print('\n'.join(lines[:30]))
