// Copyright 2026 The Roc Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! AOT control for the bitmap JIT benchmark: identical kernel ABI and algorithm.
//! Only the fixed benchmark query is specialized here; this is not an interpreter.
use arrow::datatypes::SchemaRef;
use roc::jit::{NativeBatchKernel, PredicateKernel};

pub fn aot(threshold: i64, schema: SchemaRef) -> NativeBatchKernel {
    let predicate: PredicateKernel = match threshold {
        -500 => roc_bitmap_aot_reject,
        i64::MIN => predicate::<{ i64::MIN }>,
        0 => predicate::<0>,
        500 => predicate::<500>,
        _ => panic!("unsupported benchmark threshold"),
    };
    // SAFETY: static Rust functions below implement the exact bitmap contracts
    // for input table [x, y] and one non-null Int64 result column. They return
    // status codes, do not unwind, and retain no pointers. Their constants are
    // specialized at AOT compile time, just as they are embedded in JIT code.
    assert_eq!(schema.fields().len(), 1);
    assert_eq!(
        schema.field(0).data_type(),
        &arrow::datatypes::DataType::Int64
    );
    unsafe { NativeBatchKernel::from_aot_kernels(vec![0, 1], schema, predicate, project) }
}

// Stable symbol for the diagnostics disassembly. This is the actual function
// pointer called by the -500 benchmark, not a separately compiled approximation.
#[unsafe(no_mangle)]
unsafe extern "C" fn roc_bitmap_aot_reject(
    columns: *const *const i64,
    n: usize,
    masks: *mut u64,
) -> usize {
    // SAFETY: this wrapper forwards the exact predicate ABI contract.
    unsafe { predicate::<-500>(columns, n, masks) }
}

unsafe extern "C" fn predicate<const THRESHOLD: i64>(
    columns: *const *const i64,
    n: usize,
    masks: *mut u64,
) -> usize {
    // SAFETY: the shared batch wrapper checks column lengths and mask capacity.
    unsafe {
        let x = *columns;
        let mut base = 0;
        let mut count = 0;
        while n - base >= 64 {
            let mut mask = 0_u64;
            // Same 64-row bitmap algorithm and ABI as the CLIF emitter.
            // LLVM vectorizes this scalar source; the optimized AArch64 JIT
            // expresses comparison and mask compaction with explicit SIMD.
            macro_rules! pack { ($($lane:expr),*) => { $(
                mask |= ((*x.add(base + $lane) < THRESHOLD) as u64) << $lane;
            )* }; }
            pack!(
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
                44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63
            );
            *masks.add(base / 64) = mask;
            count += mask.count_ones() as usize;
            base += 64;
        }
        if base < n {
            let mut mask = 0_u64;
            for row in base..n {
                mask |= ((*x.add(row) < THRESHOLD) as u64) << (row - base);
            }
            *masks.add(base / 64) = mask;
            count += mask.count_ones() as usize;
        }
        count
    }
}

unsafe extern "C" fn project(
    columns: *const *const i64,
    n: usize,
    masks: *const u64,
    outputs: *const *mut i64,
) -> usize {
    // SAFETY: masks were generated by predicate, with zero high tail bits;
    // the common wrapper allocated exactly their popcount output elements.
    unsafe {
        let x = *columns;
        let y = *columns.add(1);
        let output = *outputs;
        let mut count = 0;
        let mut base = 0;
        while base < n {
            let width = (n - base).min(64);
            let end = base + width;
            let mut bits = *masks.add(base / 64);
            if bits != 0 {
                let full = u64::MAX >> (64 - width);
                if bits == full {
                    for row in base..end {
                        let Some(value) = (*x.add(row))
                            .checked_mul(3)
                            .and_then(|v| v.checked_add(*y.add(row)))
                        else {
                            return usize::MAX;
                        };
                        *output.add(count) = value;
                        count += 1;
                    }
                } else {
                    while bits != 0 {
                        let row = base + bits.trailing_zeros() as usize;
                        let Some(value) = (*x.add(row))
                            .checked_mul(3)
                            .and_then(|v| v.checked_add(*y.add(row)))
                        else {
                            return usize::MAX;
                        };
                        *output.add(count) = value;
                        count += 1;
                        bits &= bits - 1;
                    }
                }
            }
            base = end;
        }
        count
    }
}
